# Generated by Django 4.2.7 on 2023-12-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('pic', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
