# Generated by Django 4.2.7 on 2023-12-08 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0003_message_user_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rooms',
            field=models.CharField(default=str, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 8, 10, 18, 19, 508413)),
        ),
    ]
