# Generated by Django 4.2.7 on 2023-12-08 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0004_users_rooms_alter_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='user_name',
            field=models.CharField(default=str, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 8, 11, 1, 41, 501193)),
        ),
    ]
