# Generated by Django 4.2.7 on 2023-12-08 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0005_remove_users_rooms_room_user_name_alter_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.CharField(max_length=100000)),
                ('rooms_id', models.CharField(max_length=100000)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 8, 11, 55, 43, 185181)),
        ),
    ]
