# Generated by Django 4.2.7 on 2023-12-08 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0006_users_rooms_remove_room_user_name_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 8, 11, 57, 58, 606801)),
        ),
    ]
